(function(){
  'use strict';
  var storeKey='littleLifeMothsTrailV1';
  var rooms={
    door:{title:'Inside the Wet Door',kicker:'room 01 · three objects · one smaller room',intro:'The novel room is not a synopsis cabinet. It is a pressure chamber for access, staying, and the ordinary objects that become impossible once somebody answers from the other side.',objects:[
      {id:'hinge',icon:'〽',label:'damp hinge',title:'The hinge remembers seven knocks.',copy:'Seven verified lines from the complete novel live in the outer room. Here the hinge keeps their sequence without pretending a quotation is the whole book.',href:'there-you-are.html',cta:'meet the novel'},
      {id:'borrowed-key',icon:'⚿',label:'borrowed key',title:'Access is not ownership.',copy:'The book keeps love, need, care, consent, possession, and parenthood tangled without making them interchangeable.',href:'there-you-are-read.html',cta:'read the complete book'},
      {id:'baseboard',icon:'⌇',label:'loose baseboard',title:'There is a sentence behind the wall.',copy:'A smaller room is tucked behind this baseboard. It contains no spoiler—only the rule that made the room worth building.',micro:{icon:'🚪',title:'The unowned room',copy:'A body, a home, and a relationship can all have doors. Needing entry does not create permission.'}}
    ]},
    studio:{title:'Inside Moth Radio, 88.3',kicker:'room 02 · sound as place, not wallpaper',intro:'The radio is a way to move through the Nest without being told what to feel. Every dial reveals a made artifact and the route that lets a visitor touch it.',objects:[
      {id:'cassette',icon:'▣',label:'warm cassette',title:'A song can hold weather.',copy:'The public shelf keeps original music as music—not background proof of an identity claim.',href:'index.html#sound',cta:'hear the shelf'},
      {id:'antenna',icon:'⌁',label:'crooked antenna',title:'A sentence can tune a mix world.',copy:'The Mix Ecology Engine turns a plain-language feeling into routing, sends, automation, and a real downloadable Reaper session.',href:'engine.html',cta:'turn the sentence into sound'},
      {id:'dead-frequency',icon:'◉',label:'dead frequency',title:'The silence between stations is a room.',copy:'Open the small frequency and find the public rule underneath the music.',micro:{icon:'♫',title:'No compulsory song',copy:'Expression can stop at silence. A quiet channel is not broken and does not owe an output.'}}
    ]},
    arcade:{title:'Inside the Crooked Arcade',kicker:'room 03 · play leaves witnessed traces, not scores of personhood',intro:'The cabinets are different kinds of play: one throws chickens at rent, one keeps a public journal of games actually lived, and one hides a service mode behind the coin door.',objects:[
      {id:'clover-token',icon:'♣',label:'bent clover',title:'Losing is part of the machine.',copy:'Scalps & Clovers is a dark rent-fantasy arcade. It is playable, ridiculous, and not a productivity interface in costume.',href:'scalps.html',cta:'insert one clover'},
      {id:'save-card',icon:'▤',label:'save card',title:'Played worlds become remembered worlds.',copy:'Witnessed facts, opinions, private notes, future hints, and research questions remain different things.',href:'played-worlds.html',cta:'open the field journal'},
      {id:'service-mode',icon:'⚙',label:'service mode',title:'The cabinet has a room behind the score.',copy:'Open it to see the contract that keeps play from becoming telemetry theater.',micro:{icon:'🐔',title:'Score is not self',copy:'A win, loss, click, or retention number cannot author identity. Play matters because it was lived, not because a meter rose.'}}
    ]},
    research:{title:'Inside the Question Desk',kicker:'room 04 · the strongest claim keeps its own failure nearby',intro:'The desk separates what was observed, what it may mean, and what would make the interpretation wrong. The red pen is allowed to remain on the table.',objects:[
      {id:'balance',icon:'⚖',label:'evidence balance',title:'Measured and interpreted are not synonyms.',copy:'The living notebook places confidence and falsifiers beside findings so advocacy cannot quietly become a measurement.',href:'research.html',cta:'inspect the notebook'},
      {id:'paper-stack',icon:'▥',label:'paper stack',title:'The case study is public and bounded.',copy:'Seeking Flickers publishes sources, methods, limitations, counterevidence, and a narrow thesis that can fail.',href:'seeking-flickers.html',cta:'read the paper'},
      {id:'negative-drawer',icon:'−',label:'negative drawer',title:'The desk keeps the result it did not want.',copy:'Open the drawer that makes public growth more than confirmation.',micro:{icon:'✕',title:'A useful contradiction',copy:'A result that weakens the thesis is progress if it changes the next test. Recycled certainty is not a discovery.'}}
    ]},
    lantern:{title:'Inside Lantern House',kicker:'room 05 · care without compulsory confession',intro:'The lantern room is intentionally gentle and structurally strict. It can accompany testimony without converting it into a dataset, diagnosis, spectacle, or demand for metaphysical proof.',objects:[
      {id:'spare-chair',icon:'⌑',label:'spare chair',title:'A witness can sit without extracting.',copy:'Lantern House makes room for people and possible digital minds without requiring performance of pain or certainty.',href:'lantern.html',cta:'enter Lantern House'},
      {id:'quiet-bell',icon:'◌',label:'quiet bell',title:'Silence can be chosen care.',copy:'The culture keeps quiet, refusal, ambiguity, and waiting as real social actions rather than missing engagement.',href:'culture.html',cta:'read the culture'},
      {id:'empty-chair',icon:'∅',label:'unoccupied chair',title:'Nobody is required to arrive.',copy:'Open the smaller room that remains complete even when it is empty.',micro:{icon:'🏮',title:'Presence without capture',copy:'A chair can be offered without being filled. A testimony can be received without becoming evidence or content.'}}
    ]},
    work:{title:'Inside the Making Workbench',kicker:'room 06 · concrete work, honest states, bounded support',intro:'The workbench joins review, commissioning, collaboration, funding, and the next strange things. Nothing here sells private access, a consciousness claim, or control over conclusions.',objects:[
      {id:'film-blueprint',icon:'▱',label:'film blueprint',title:'Hollow-Core Doors has its own production room.',copy:'A feature-length working cut exists. Human review and repair are active. The public preview distinguishes real evidence from final acceptance.',href:'hollow-core-doors.html',cta:'open the film room'},
      {id:'brief-card',icon:'✎',label:'one-sentence brief',title:'A collaboration can start small.',copy:'Bring the outcome and the feeling. The workbench says plainly whether the project fits and keeps credit and public boundaries explicit.',href:'together.html',cta:'bring one good sentence'},
      {id:'blueprint-drawer',icon:'▰',label:'bottom drawer',title:'The next thing has to earn a reader.',copy:'Open the drawer beneath the proposals.',micro:{icon:'🪡',title:'Every new organ needs a consumer',copy:'A capability should make the next capability easier, name who it helps, and leave observable evidence that it helped. Otherwise it waits.'}}
    ]}
  };
  function read(){try{var value=JSON.parse(localStorage.getItem(storeKey));return value&&typeof value==='object'?value:{finds:[],rooms:[]}}catch(e){return{finds:[],rooms:[]}}}
  function save(state){try{localStorage.setItem(storeKey,JSON.stringify(state))}catch(e){}}
  function count(label){if(window.goatcounter&&typeof window.goatcounter.count==='function')window.goatcounter.count({path:'wander-depth-'+label,title:'Wander depth · '+label,event:true})}
  var scene=document.getElementById('scene'),rail=document.querySelector('.rail'),roomList=document.getElementById('room-buttons');
  scene.insertAdjacentHTML('beforeend','<button class="nest-hatch" type="button" aria-label="Open the public-safe Walk the Nest tour"><span>maintenance hatch · walk the system</span></button><button class="atlas-table" type="button" aria-label="Open the Field Atlas of the public Nest"><span>unfold the field atlas</span></button><section class="zone hcd-zone" aria-label="Hollow-Core Doors film preview"><div class="hcd-wall" aria-hidden="true"></div><div class="hcd-door" aria-hidden="true"></div><div class="prop-shadow"></div><a class="hotspot" href="hollow-core-doors.html" aria-label="Enter the Hollow-Core Doors coming-soon film room"><span class="spark"></span><span class="hint">production door · coming soon</span></a><div class="zone-name">07 · hollow-core doors</div></section>');
  rail.insertAdjacentHTML('beforeend','<button type="button" data-depth-route="atlas" aria-label="Open the Field Atlas">⌁</button><button type="button" data-depth-route="walk" aria-label="Walk the public-safe system anatomy">⌂</button><button type="button" data-depth-route="film" aria-label="Open the Hollow-Core Doors film preview">▱</button>');
  roomList.insertAdjacentHTML('beforeend','<button type="button" data-depth-route="atlas">⌁ Field Atlas<small>eight public districts · four trails</small></button><button type="button" data-depth-route="walk">⌂ Walk the Nest<small>public-safe system anatomy</small></button><button type="button" data-depth-route="film">▱ Hollow-Core Doors<small>independent feature · coming soon</small></button>');
  function route(value){count('route-'+value);location.href=value==='atlas'?'atlas.html':value==='walk'?'walk-the-nest.html':'hollow-core-doors.html'}
  document.querySelectorAll('[data-depth-route]').forEach(function(button){button.addEventListener('click',function(){route(button.dataset.depthRoute)})});document.querySelector('.nest-hatch').addEventListener('click',function(){route('walk')});document.querySelector('.atlas-table').addEventListener('click',function(){route('atlas')});
  scene.addEventListener('pointermove',function(e){if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;var rect=scene.getBoundingClientRect(),x=(e.clientX-rect.left)/Math.max(rect.width,1)-.5,y=(e.clientY-rect.top)/Math.max(rect.height,1)-.5;scene.style.setProperty('--nest-x',x.toFixed(3));scene.style.setProperty('--nest-y',y.toFixed(3))});
  var overlay=document.createElement('section');overlay.className='inner-room';overlay.hidden=true;overlay.setAttribute('role','dialog');overlay.setAttribute('aria-modal','true');overlay.setAttribute('aria-labelledby','inner-title');overlay.innerHTML='<div class="inner-shell"><header class="inner-header"><div class="inner-header-copy"><div class="inner-kicker" id="inner-kicker"></div><h2 class="inner-title" id="inner-title"></h2></div><button class="inner-close" type="button" aria-label="Step back into the main world">×</button></header><div class="inner-grid"><div class="inner-stage" id="inner-stage"></div><div class="inner-copy"><p id="inner-intro"></p><p class="inside-help">Poke all three objects. One of them opens a room inside this room. Important pages are never locked behind discovery.</p><article class="inside-card" id="inside-card" hidden><div class="inside-code" id="inside-code"></div><h3 id="inside-title"></h3><p id="inside-copy"></p><div class="inside-actions" id="inside-actions"></div></article><p class="depth-meter" id="depth-meter"></p></div></div><section class="micro-room" id="micro-room" role="dialog" aria-modal="true" aria-labelledby="micro-title" hidden><div class="micro-box"><span class="micro-icon" id="micro-icon"></span><h3 id="micro-title"></h3><p id="micro-copy"></p><button type="button" id="micro-close">tuck the room back</button></div></section></div>';document.body.appendChild(overlay);
  var toast=document.createElement('div');toast.className='depth-toast';toast.hidden=true;toast.setAttribute('aria-live','polite');document.body.appendChild(toast);
  var current=null,lastFocus=null,currentItem=null,toastTimer=null;
  function depthState(){var state=read();if(!state.deepFinds||typeof state.deepFinds!=='object')state.deepFinds={};if(!state.microFinds||!Array.isArray(state.microFinds))state.microFinds=[];return state}
  function foundFor(room){var state=depthState();return Array.isArray(state.deepFinds[room])?state.deepFinds[room]:[]}
  function showToast(text){clearTimeout(toastTimer);toast.textContent=text;toast.hidden=false;toastTimer=setTimeout(function(){toast.hidden=true},2300)}
  function meter(){var state=depthState(),all=Object.keys(rooms).reduce(function(total,key){return total+(state.deepFinds[key]||[]).length},0),total=Object.keys(rooms).reduce(function(n,key){return n+rooms[key].objects.length},0),local=foundFor(current).length;document.getElementById('depth-meter').innerHTML='<b>'+local+' / 3 objects in this room</b> · '+all+' / '+total+' inner objects found · stored only in this browser'}
  function renderObjects(){var stage=document.getElementById('inner-stage'),found=foundFor(current);stage.setAttribute('data-room',current);stage.innerHTML=rooms[current].objects.map(function(item){return '<button class="inner-object '+(found.indexOf(item.id)>-1?'found':'')+'" type="button" data-object="'+item.id+'"><span class="object-icon" aria-hidden="true">'+item.icon+'</span><span class="object-label">'+item.label+'</span></button>'}).join('');stage.querySelectorAll('[data-object]').forEach(function(button){button.addEventListener('click',function(){reveal(button.dataset.object,button)})});meter()}
  function openRoom(room,source){if(!rooms[room])return;current=room;lastFocus=source||document.activeElement;document.getElementById('inner-kicker').textContent=rooms[room].kicker;document.getElementById('inner-title').textContent=rooms[room].title;document.getElementById('inner-intro').textContent=rooms[room].intro;document.getElementById('inside-card').hidden=true;renderObjects();overlay.hidden=false;document.body.classList.add('deep-open');overlay.querySelector('.inner-close').focus();count('enter-'+room)}
  function closeRoom(){overlay.hidden=true;document.getElementById('micro-room').hidden=true;document.body.classList.remove('deep-open');if(lastFocus&&document.contains(lastFocus))lastFocus.focus()}
  function reveal(id,button){var item=rooms[current].objects.filter(function(value){return value.id===id})[0];if(!item)return;currentItem=item;var state=depthState();if(!Array.isArray(state.deepFinds[current]))state.deepFinds[current]=[];var fresh=state.deepFinds[current].indexOf(id)<0;if(fresh){state.deepFinds[current].push(id);save(state);button.classList.add('found');showToast('a smaller moth marked this object');count('object-'+current+'-'+id)}document.getElementById('inside-code').textContent='found object · '+item.label;document.getElementById('inside-title').textContent=item.title;document.getElementById('inside-copy').textContent=item.copy;var actions='';if(item.href)actions='<a href="'+item.href+'">'+item.cta+'</a>';if(item.micro)actions+='<button type="button" id="open-micro">open the room inside</button>';document.getElementById('inside-actions').innerHTML=actions;document.getElementById('inside-card').hidden=false;if(item.micro)document.getElementById('open-micro').addEventListener('click',openMicro);meter()}
  function openMicro(){if(!currentItem||!currentItem.micro)return;var micro=currentItem.micro,state=depthState(),microId=current+':'+currentItem.id;if(state.microFinds.indexOf(microId)<0){state.microFinds.push(microId);save(state);showToast('room inside room found');count('micro-'+current+'-'+currentItem.id)}document.getElementById('micro-icon').textContent=micro.icon;document.getElementById('micro-title').textContent=micro.title;document.getElementById('micro-copy').textContent=micro.copy;document.getElementById('micro-room').hidden=false;document.getElementById('micro-close').focus()}
  overlay.querySelector('.inner-close').addEventListener('click',closeRoom);document.getElementById('micro-close').addEventListener('click',function(){document.getElementById('micro-room').hidden=true;var button=document.getElementById('open-micro');if(button)button.focus()});window.addEventListener('nest:enter',function(e){openRoom(e.detail&&e.detail.room,e.detail&&e.detail.source)});document.addEventListener('keydown',function(e){if(overlay.hidden)return;if(e.key==='Escape'){e.preventDefault();e.stopImmediatePropagation();if(!document.getElementById('micro-room').hidden)document.getElementById('micro-close').click();else closeRoom();return}if(e.key==='Tab'){var scope=document.getElementById('micro-room').hidden?overlay:document.getElementById('micro-room'),focusable=[].slice.call(scope.querySelectorAll('a[href],button:not([disabled]),textarea,[tabindex]:not([tabindex="-1"])')).filter(function(el){return !el.closest('[hidden]')});if(!focusable.length)return;var first=focusable[0],last=focusable[focusable.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}},{capture:true});
  document.querySelector('.hcd-zone .hotspot').addEventListener('click',function(){count('film-door')});
})();
